package de.jomlua.utils;

public enum Material {
    // I = Items / B = Block
    // Enum_ITEM("minecraft:enum_Item", "Enum Item", "I", 5342),
    Air("minecraft:air", "Air","B", 0),
    Stone("minecraft:stone", "Stone", "B",1),
    Cobblestone("minecraft:cobblestone","Cobblestone", "B",2),
    Acacia_Button("minecraft:acacia_button", "Acacia Button","B", 1000),
    Acacia_Boat("minecraft:acacia_boat", "Acacia Boat","B", 1001),
    Acacia_Door("minecraft:acacia_door", "Acacia Door", "B",430),
    Acacia_Fence("minecraft:acacia_fence", "Acacia Fence","B", 192),
    Acacia_Fence_Gate("minecraft:acacia_fence_gate", "Acacia Fence Gate","B", 187),
    Acacia_Leaves("minecraft:acacia_leaves", "Acacia Leaves","B", 1002),
    Acacia_Log("minecraft:acacia_log", "Acacia Log","B", 1003),
    Acacia_Planks("minecraft:acacia_planks", "Acacia Planks","B", 1004),
    Acacia_Pressure_Plate("minecraft:acacias_pressure_plate", "Acacia Pressure Plate","B", 1005),
    Acacia_Sapling("minecraft:acacia_sapling","Acacia Sapling","B", 1006),
    ACACIA_SIGN("minecraft:acacia_sign", "Acacia Sign","B", 1007),
    ACACIA_SLAB("minecraft:acacia_slab", "Acacia Slab","B", 1008),
    ACACIA_STAIRS("minecraft:acacia_stairs", "Acacia Stairs","B", 1009),
    ACACIA_TRAPDOOR("minecraft:acacia_trapdoor", "Acacia Trapdoor","B", 1010),
    ACACIA_WALL_SIGN("minecraft:acacia_wall_sign", "Acacia Wall Sign","B", 1011),
    ACACIA_WOOD("minecarft:acacia_wood", "Acacia Wood","B", 1012),
    ACTIVATOR_RAIL("minecraft:activator_rail", "Activator Rail","B", 1013),
    ALLAY_SPAWN_EGG("minecraft:allay_spawn_egg", "Allay Spawn Egg","I", 1014),
    ALLIUM("minecraft:allium", "Allium","I", 1015),
    AMETHYST_BLOCK("minecraft:amethyst_block", "Amethyst Block","B", 1016),
    AMETHYST_CLUSTER("minecraft:amethyst_cluster", "Amethyst Cluster", "B", 1017),
    AMETHYST_SHARD("minecaft:amethyst_shard", "Amethyst Shard", "I", 1018),
    ANCIENT_DEBRIS("minecraft:ancient_debris", "Ancient Debris", "B", 1019),
    ANDESITE("minecraft:andedite", "Andesite", "B", 1020),
    ANDESITE_SLAB("minecraft:andesite_slab","Andesite Slab", "B",1021),
    ANDESITE_STAIRS("minecraft:andesite_stairs", "Andesite Stairs", "B", 1022),
    ANDESITE_WALL("minecraft:andesite_wall", "Andesite Wall", "B", 1023),
    ANVIL("minecraft:anvil", "Anvil","B", 1024),
    APPLE("minecraft:apple", "Apple", "I", 1025),
    ARMOR_STAND("minecraft:armor_stand", "Armor Stand", "B", 1026),
    ARROW("minecraft:arrow", "Arrow", "I", 1027),
    ATTACHED_MELON_STEM("minecraft:attached_melon_stem", "Melone Seeds", "I", 1028),
    ATTACHED_PUMPKIN_STEM("minecraft:attached_pumpkin_stem", "Pumkin Seeds", "I", 1029),
    AXOLOTL_BUCKET("minecraft:axolotl_bucket", "Axolotl Bucket", "I", 1030),
    AXOLOTL_SPAWN_EGG("minecraft:axolotl_spawn_egg", "Axolotl Spawn Egg", "I", 1031),
    AZALEA("minecraft:azalea", "Azalea", "B", 1032),
    AZALEA_LEAVES("minecraft:azalea_leaves", "Azalea Leaves", "B", 1033),
    AZURE_BLUET("minecraft:azure_bluet", "Azure Bluet", "B", 1034),
    BAKED_POTATO("minecraft:baked_potato", "Baked Potato", "I", 1035),
    BAMBOO("minecraft:bamboo", "Bamboo", "B", 1036),
    BAMBOO_SAPLING("minecraft:bamboo_sapling", "Bamboo Sapling", "I",1037),
    BARREL("minecraft:barrel", "Barrel", "B", 1038),
    BARRIER("minecraft:barrier", "Barrier", "B", 1039),
    BASALT("minecraft:basalt", "Basalt", "B", 1040),
    BAT_SPAWN_EGG("minecraft:bat_spawn_egg", "Bat Spawn Egg", "I", 1041),
    BEACON("minecraft:beacon", "Beacon", "B", 1042),
    BEDROCK("minecraft:bedrock", "Bedrock" ,"B", 1043),
    BEE_NEST("minecraft:bee_nest", "Bee Nest", "B", 1044),
    BEE_SPAWN_EGG("minecraft:bee_spawn_egg", "Bee Spawn Egg", "I", 1045),
    BEEF("minecraft:beef", "Beef", "I", 1046),
    BEEHIVE("minecraft:beehive", "Beehive", "B", 1047),
    BEETROOT("minecraft:beetroot", "Beetroot", "I", 1048),
    BEETROOT_SEEDS("minecraft:beetroot_seed", "Beetroot Seed", "I", 1049),
    BEETROOT_SOUP("minecraft:beetroot_soup", "Beetroot Soup", "I", 1050),
    BEETROOTS("minecraft:beetroots", "Beetroots (E)", "I", 1051),
    BELL("minecraft:bell", "Bell", "B", 1052),
    BIG_DRIPLEAF("minecraft:big_dripleaf", "Big Dripleaf", "I", 1053),
    BIG_DRIPLEAF_STEM("minecraft:big_dripleaf_stem", "Big Dripleaf Stem", "I", 1054),
    BIRCH_BOAT("minecraft:birch_boat", "Birch Boat", "B", 1055),
    BIRCH_BUTTON("minecraft:birch_button", "Birch Button", "B", 1056),
    BIRCH_CHEST_BOAT("minecraft:birch_chest_boat", "Birch Chest Boat", "B", 1057),
    BIRCH_DOOR("minecraft:birch_door", "Birch Door", "B", 1058),
    BIRCH_FENCE("minecraft:birch_fence", "Birch Fence", "B", 1059),
    BIRCH_FENCE_GATE("minecraft:birch_fence_gate", "Birch Fence Gate", "B",1060),
    BIRCH_LEAVES("minecraft:birch_leaves", "Birch Leaves", "B", 1061),
    BIRCH_LOG("minecraft:birch_log", "Birch Log", "B", 1062),
    BIRCH_PLANKS("minecraft:birch_planks", "Birch Planks", "B", 1063),
    BIRCH_PRESSURE_PLATE("minecraft:birch_pressure_plate", "Birch Pressure Plate", "B", 1064),
    BIRCH_SAPLING("minecraft:birch_sapling", "Birch Sapling", "I", 1065),
    BIRCH_SIGN("minecraft:birch_sign", "Birch Sign", "B", 1066),
    BIRCH_SLAB("minecraft:birch_slab", "Birch Slab", "B", 1067),
    BIRCH_STAIRS("minecraft:birch_stairs", "Birch Stairs", "B", 1068),
    BIRCH_TRAPDOOR("minecraft:birch_trapdoor", "Birch Trapdoor", "B", 1069),
    BIRCH_WALL_SIGN("minecraft:birch_wall_sign", "Birch Wall Sign", "B", 1070),
    BIRCH_WOOD("minecraft:birch_wood", "Birch Wood", "B", 1071),
    BLACK_BANNER("minecraft:black_banner", "Black Banner", "B", 1072),
    BLACK_BED("minecraft:black_bed", "Black Bed", "B", 1073),
    BLACK_CANDLE("minecraft:black_candle", "Black Candle", "B", 1074),
    BLACK_CANDLE_CAKE("minecraft:black_candle_cake", "Black Candle Cake", "B", 1075),
    BLACK_CARPET("minecraft:black_carpet", "Black Carpet", "B", 1076),
    BLACK_CONCRETE("minecraft:black_concrete", "Black Concrete", "B", 1077),
    BLACK_CONCRETE_POWDER("minecraft:black_concrete_powder", "Black Concrete Powder", "B", 1078),
    BLACK_DYE("minecraft:black_dye", "Black Dye", "I", 1079),
    BLACK_GLAZED_TERRACOTTA("minecraft:black_glazed_terracotta", "Black Glazed Terracotta", "B", 1080),
    BLACK_SHULKER_BOX("minecraft:black_shulker_box", "Black Shulker Box", "B", 1081),
    BLACK_STAINED_GLASS("minecraft:black_stained_glass", "Black Stained Glas", "B", 1082),
    BLACK_STAINED_GLASS_PANE("minecraft:black_stained_glass_pane", "Black Stained Glas Pane", "B", 1083),
    BLACK_TERRACOTTA("minecraft:black_terracotta", "Black Terracotter", "B", 1084),
    BLACK_WALL_BANNER("minecraft:black_wall_banner", "Black Wall Banner", "B", 1085),
    BLACK_WOOL("minecraft:black_wool", "Black Wool", "B", 1086),
    BLACKSTONE("minecraft:blackstone", "Blackstone", "B", 1087),
    BLACKSTONE_SLAB("minecraft:blackstone_slab", "Blackstone Slab", "B", 1088),
    BLACKSTONE_STAIRS("minecraft:blackstone_stairs", "Blackstone Stairs", "B", 1089),
    BLACKSTONE_WALL("minecraft:blackstone_wall", "Blackstone Wall", "B", 1090),
    BLAST_FURNACE("minecraft:blast_furnace", "Blast Furnace", "B", 1091),
    BLAZE_POWDER("minecraft:blaze_powder", "Blaze Powder", "I", 1092),
    BLAZE_ROD("minecraft:blaze_rod", "Blaze Rod", "I", 1093),
    BLAZE_SPAWN_EGG("minecraft:blaze_spawn_egg", "Blaze SPawn Egg", "I", 1094),
    BLUE_BANNER("minecraft:blue_banner", "Blue Banner", "B", 1095),
    BLUE_BED("minecraft:blue_bed", "Blue Bed", "B", 1096),
    BLUE_CANDLE("minecraft:blue_candle", "Blue Candle", "B", 1097),
    BLUE_CANDLE_CAKE("minecraft:blue_candle_cake", "Blue Candle Cake", "B", 1098),
    BLUE_CARPET("minecraft:blue_carpet", "Blue Crpet", "B", 1099),
    BLUE_CONCRETE("minecraft:blue_concrete", "Blue Concrete", "B", 1100),
    BLUE_CONCRETE_POWDER("minecraft:blue_concrete_powder", "Blue Concrete Powder", "B", 1101),
    BLUE_DYE("minecraft:blue_dye", "Blue Dey", "I", 1102),
    BLUE_GLAZED_TERRACOTTA("minecraft:blue_glazed_terracotta", "Blue Glazed Terracotta", "B", 1103),
    BLUE_ICE("minecraft:blue_ice", "Blue Ice", "B", 1104),
    BLUE_ORCHID("minecraft:blue_orchid", "Blue Orchid", "B", 1105),
    BLUE_SHULKER_BOX("minecraft:blue_shulker_box", "Blue Shulker Box", "B", 1106),
    BLUE_STAINED_GLASS("minecraft:blue_stained_glass", "Blue Stained Glass", "B", 1107),
    BLUE_STAINED_GLASS_PANE("minecraft:blue_stained_glas_pane", "Blue Stained Glas Pane", "B", 1108),
    BLUE_TERRACOTTA("minecraft:blue_terracotta", "Blue Terracotta", "B", 1109),
    BLUE_WALL_BANNER("minecraft:blue_wall_banner", "Blue Wall Banner", "B", 1110),
    BLUE_WOOL("minecraft:blue_wool", "Blue_wool", "B", 1111),
    BONE("minecraft:bone", "Bone", "I", 1112),
    BONE_BLOCK("minecraft:bone_block", "Bone Block", "B", 1113),
    BONE_MEAL("minecraft:bone_meal", "Bone Meal", "I", 1114),
    BOOK("minecraft:book", "Book", "I", 1115),
    BOOKSHELF("minecraft:bookshelf", "Bookshelf", "B", 1116),
    BOW("minecraft:bow", "Bow", "I", 1117),
    BOWL("minecraft:bowl", "Bowl", "I", 1118),
    BRAIN_CORAL("minecraft:brain_coral", "Brain Coral", "I", 1119),
    BRAIN_CORAL_BLOCK("minecraft:brain_coral_block", "Brain Coral Block", "B", 1120),
    BRAIN_CORAL_FAN("minecraft:brain_coral_fan", "Brain Coral Fan", "B", 1121),
    BRAIN_CORAL_WALL_FAN("minecraft:brain_coral_wall_fan", "Brain Coral Wall Fan", "B", 1122),
    BREAD("minecraft:bread", "Bread", "I", 1123),
    BREWING_STAND("minecraft:brewing_stand", "Brewing Stand", "B", 1124),
    BRICK("minecraft:brick", "Brick", "B", 1125),
    BRICK_SLAB("minecraft:brick_slab", "Brick Slab", "B", 1126),
    BRICK_STAIRS("minecraft:brick_stairs", "Brick Stairs", "B", 1127),
    BRICK_WALL("minecraft:brick_wall", "Brick Wall", "B", 1128),
    BRICKS("minecraft:bricks", "Bricks", "B", 1129),
    BROWN_BANNER("minecraft:brown_banner", "Brown Banner", "B", 1130),
    BROWN_BED("minecraft:brown_bed", "Brown Bed", "B", 1131),
    BROWN_CANDLE("minecraft:brown_candle", "Brown Candle", "B", 1132),
    BROWN_CANDLE_CAKE("minecraft:brown_candle_cake", "Brown Candle Cake", "B", 1133),
    BROWN_CARPET("minecraft:brown_carpet", "Brown Carpet", "B", 1134),
    BROWN_CONCRETE("minecraft:brown_concrete", "Brown Concrete", "B", 1135),
    BROWN_CONCRETE_POWDER("minecraft:brown_concrete_powder", "Brown Concrete Powder", "B", 1136),
    BROWN_DYE("minecraft:brown_dye", "Brown Dye", "I", 1137),
    BROWN_GLAZED_TERRACOTTA("minecraft:brown_glazed_terracotta", "Brown Glazed Terracotta", "B", 1138),
    BROWN_MUSHROOM("minecraft:brown_mushroom", "Brown Mushroom", "B", 1139),
    BROWN_MUSHROOM_BLOCK("minecraft:brown_mushroom_block", "Brown Mushroom Block", "B", 1140),
    BROWN_SHULKER_BOX("minecraft:brown_shulker_box", "Brown Shulker Box", "B", 1141),
    BROWN_STAINED_GLASS("minecraft:brown_stained_glas", "Brown Stained Glass", "B", 1142),
    BROWN_STAINED_GLASS_PANE("minecraft:brown_stained_glass_pane", "Brown Stained Glass Pane", "B", 1143),
    BROWN_TERRACOTTA("minecraft:brown_terracotta", "Brown Terracotta", "B", 1144),
    BROWN_WALL_BANNER("minecraft:brown_wall_banner", "Brown Wall Banner", "B", 1145),
    BROWN_WOOL("minecraft:brown_wool", "Brown Wool", "B", 1146),
    BUBBLE_COLUMN("minecraft:bubble_column", "Bubble Column", "B", 1147),
    BUBBLE_CORAL("minecraft:bubble_coral", "Bubble Coral", "B", 1148),
    BUBBLE_CORAL_BLOCK("minecraft:bubble_coral_block", "Bubble Coral Block", "B", 1149),
    BUBBLE_CORAL_FAN("minecraft:bubble_coral_fan", "Bubble Coral Fan", "B", 1150),
    BUBBLE_CORAL_WALL_FAN("minecraft:bubble_coral_wall_fan", "Bubble Coral Wall Fan", "B", 1151),
    BUCKET("minecraft:bucket", "Bucket", "I", 1152),
    BUDDING_AMETHYST("minecraft:budding_amethyst", "Budding Amethyst", "B", 1153),
    BUNDLE("minecraft:bundle", "Bundle", "I", 1154),
    CACTUS("minecraft:cactus", "Cactus", "B", 1154),
    CAKE("minecraft:cake", "Cake", "B",1155),
    CALCITE("minecraft:calcite", "Calcite", "B",1156),
    CAMPFIRE("minecraft:campfire", "Campfire", "B",1157),
    CANDLE("minecraft:candle", "Candle", "B",1158),
    CANDLE_CAKE("minecraft:candle_cake", "Candle Cake", "B",1159),
    CARROT("minecraft:carrot", "Carrot", "I",1160),
    CARROT_ON_A_STICK("minecraft:carrot_on_a_stick", "Carrot On A Stick", "I",1161),
    CARROTS("minecraft:carrots", "Carrots", "C",1162),
    CARTOGRAPHY_TABLE("minecraft:cartography_table", "Cartography Table", "B",1163),
    CARVED_PUMPKIN("minecraft:carved_pumpkin", "Carved Pumpkin", "B",1164),
    CAT_SPAWN_EGG("minecraft:cat_spawn_egg", "Cat Spawn Egg", "I",1165),
    CAULDRON("minecraft:cauldron", "Cauldron", "B",1167),
    CAVE_AIR("minecraft:cave_air", "Cave Air", "B",1168),
    CAVE_SPIDER_SPAWN_EGG("minecraft:cave_spider_spawn_egg", "Cave Spieder Spawn Egg", "I",1169),
    CAVE_VINES("minecraft:cave_vine", "Cave vine", "B",1170),
    CAVE_VINES_PLANT("minecraft:cave_vine_plant", "Cave Vine Plant", "I",1171),
    CHAIN("minecraft:chain", "Chain", "B",1172),
    CHAIN_COMMAND_BLOCK("minecraft:chain_command_Block", "ADMIN Chain Commandblock", "B",1173),
    CHAINMAIL_BOOTS("minecraft:chainmail_boots", "Chainmail Boot", "I",1174),
    CHAINMAIL_CHESTPLATE("minecraft:chainmail_chestplate", "Chainmail Chestplate", "I",1175),
    CHAINMAIL_HELMET("minecraft:chainmail_helmet", "Chainmail Helmet", "I",1176),
    CHAINMAIL_LEGGINGS("minecraft:chainmail_leggings", "Chainmail Leggings", "B",1177),
    CHARCOAL("minecraft:charcoal", "Charcoal", "I",1178),
    CHEST_MINECART("minecraft:chest_minecart", "Chest Minecart", "B",1179),
    CHICKEN("minecraft:chicken", "Chicken", "I",1180),
    CHICKEN_SPAWN_EGG("minecraft:chicken_spawn_egg", "Chicken Spawn Egg", "I",1181),
    CHIPPED_ANVIL("minecraft:chipped_anvil", "Chipped Anvil", "B",1182),
    CHISELED_DEEPSLATE("minecraft:chiseld_deepslate", "Chiseld Deepslate", "B",1183),
    CHISELED_NETHER_BRICKS("minecraft:chiseld_nether_bricks", "Chiseld Nether Bricks", "B",1184),
    CHISELED_POLISHED_BLACKSTONE("minecraft:chiseld_polished_blackstone", "Chiseld Polished Blackstone", "B",1185),
    CHISELED_QUARTZ_BLOCK("minecraft:chiseld_quartz_block", "Chiseld Quartz Block", "B",1186),
    CHISELED_RED_SANDSTONE("minecraft:chiseld_red_sandstone", "Chiseld Red Sandstone", "B",1187),
    CHISELED_SANDSTONE("minecraft:chiseld_sandstone", "Chiseld Sandstone", "B",1188),
    CHISELED_STONE_BRICKS("minecraft:chiseld_stone_bricks", "Chiseld Stone Bricks", "B",1189),
    CHORUS_FLOWER("minecraft:chorus_flower", "Chorus Flower", "B",1190),
    CHORUS_FRUIT("minecraft:chorus_fruit", "Chorus Fruit", "I",1191),
    CHORUS_PLANT("minecraft:chorus_plant", "Chorus Plant", "I",1192),
    CLAY("minecraft:clay", "Clay", "B",1193),
    CLAY_BALL("minecraft:clay_ball", "Clay Ball", "I",1194),
    CLOCK("minecraft:clock", "Clock", "I",1195),
    COAL("minecraft:coal", "Coal", "I",1196),
    COAL_BLOCK("minecraft:coal_block", org.bukkit.Material.COAL_BLOCK.name(), "B",1197), // Todo Prüfen ob es Klappt.
    COAL_ORE("minecraft:coal_ore", "Coal Ore", "B",1198),
    COARSE_DIRT("minecraft:coarse:dirt", "Coarse Dirt", "B",1199),
    COBBLED_DEEPSLATE("minecraft:cobbled_deepslate", org.bukkit.Material.COBBLED_DEEPSLATE.name(), "B",1200),
    COBBLED_DEEPSLATE_SLAB("minecraft:cobbled_deepslate_slab", org.bukkit.Material.COBBLED_DEEPSLATE_SLAB.name(), "B", 1201),
    COBBLED_DEEPSLATE_STAIRS("minecraft:cobbled_deepslate_stairs", "Cobbled Deepslate Stairs", "B",1202),
    COBBLED_DEEPSLATE_WALL("minecraft:cobbled_deepslate_wall", "Cobbled Deepslate Wall", "B",1203),
    COBBLESTONE("minecraft:cobblestone", "Cobblestone", "B",1204),
    COBBLESTONE_SLAB("minecraft:cobblestone_slab", "Cobblestone Slab", "B",1205),
    COBBLESTONE_STAIRS("minecraft:cobblestone_stairs", "Cobblestone Stairs", "B",1206),
    COBBLESTONE_WALL("minecraft:cobblestone_wall", "Cobblestone Wall", "B",1207),
    COBWEB("minecraft:cobweb", "Cobweb", "B",1208),
    COCOA("minecraft:cocoa", "Cocoa", "B",1209),
    COCOA_BEANS("minecraft:cocoa_beans", "Cocoa Beans", "I",1210),
    COD("minecraft:cod", "Cod", "I",1211),
    COD_BUCKET("minecraft:cod_bucket", "Cod Bucket", "I",1212),
    COD_SPAWN_EGG("minecraft:cod_spawn_egg", "Cod Spawn Egg", "I",1213),
    COMMAND_BLOCK("minecraft:command_block", "Command Block", "B",1214),
    COMMAND_BLOCK_MINECART("minecraft:command_block_minecart", "Command Block Minecart", "B",1215),
    COMPARATOR("minecraft:comparator", "Comparator", "B",1216),
    COMPOSTER("minecraft:composter", "Composter", "B",1217),
    CONDUIT("minecraft:conduit", "Conduit", "B",1218),
    COOKED_BEEF("minecraft:cooked_beef", "Cooked Beef", "I",1219),
    COOKED_CHICKEN("minecraft:cooked_chicken", "Cooked Chicken", "I",1220),
    COOKED_COD("minecraft:cooked_cod", "Cooked Cod", "I",1221),
    COOKED_MUTTON("minecraft:cooked_mutton", "Cooked Mutton", "I",1222),
    COOKED_PORKCHOP("minecraft:cooked_porkchop", "Cooked Porkchop", "I",1223),
    COOKED_RABBIT("minecraft:cooked_rabbit", "Cooked Rabbit", "I",1224),
    COOKED_SALMON("minecraft:cooked_salmon", "Cooked Salmon", "I",1225),
    COOKIE("minecraft:cookie", "Cookie", "I",1226),
    COPPER_BLOCK("minecraft:copper_block", "Copper Block", "B",1227),
    COPPER_INGOT("minecraft:copper_ingot", "Copper Ingot", "I",1228),
    COPPER_ORE("minecraft:copper_ore", "Copper Ore", "B",1229),
    CORNFLOWER("minecraft:cornflower", "Cornflower", "B",1230),
    COW_SPAWN_EGG("minecraft:cow_spawn_egg", "Cow Spawn Egg", "I",1231),
    CRACKED_DEEPSLATE_BRICKS("minecraft:cracked_deepslate_bricks", "Cracked Deepslate Bricks", "B",1232),
    CRACKED_DEEPSLATE_TILES("minecraft:cracked_deepslate_tiles", "Cracker Deepslate Tiles", "B",1233),
    CRACKED_NETHER_BRICKS("minecraft:cracked_nether_bricks", "Cracked Nether Bricks", "B",1234),
    CRACKED_POLISHED_BLACKSTONE_BRICKS("minecraft:cracked_polished_blackstone_bricks", "Cracked Polished Blockstone Bricks", "B",1235),
    CRACKED_STONE_BRICKS("minecraft:cracked_stone_bricks", "Cracked Stone Bricks", "B",1236),
    CRAFTING_TABLE("minecraft:crafting_table", "Crafting Table", "B",1237),
    CREEPER_BANNER_PATTERN("minecraft:creeper_banner_pattern", "Creeper Banner Pattern", "I",1238),
    CREEPER_HEAD("minecraft:creeper_head", "Creeper Head", "B",1239),
    CREEPER_SPAWN_EGG("minecraft:creeper_spawn_egg", "Creeper Spawn Egg", "B",1240),
    CREEPER_WALL_HEAD("minecraft:creeper_wall_head", "Creeper Wall Head", "B",1241),
    CRIMSON_BUTTON("minecraft:crimson_button", "Crimson Button", "B",1242),
    CRIMSON_DOOR("minecraft:crimson_door", "Crimson Door", "B",1243),
    CRIMSON_FENCE("minecraft:crimson_fance", "Crimson Fence", "B",1244),
    CRIMSON_FENCE_GATE("minecraft:crimson_fence_gate", "Crimson Fance Gate", "B",1245),
    CRIMSON_FUNGUS("minecraft:crimson_fungus", "Crimson Fungus", "B",1246),
    CRIMSON_HYPHAE("minecraft:crimson_hyphe", "Crimson Hyphae", "B",1247),
    CRIMSON_NYLIUM("minecraft:crimson_nylium", "Crimson Nylium", "B",1248),
    CRIMSON_PLANKS("minecraft:crimson_planks", "Crimson Planks", "B",1249),
    CRIMSON_PRESSURE_PLATE("minecraft:crimson_pressure_plate", "Crimson Pressure Plate", "B",1250),
    CRIMSON_ROOTS("minecraft:crimson_roots", "Crimson Roots", "B",1251),
    CRIMSON_SIGN("minecraft:crimson_sign", "Crimson Sign", "B",1252),
    CRIMSON_STAIRS("minecraft:crimson_stairs", "Crimson Stairs", "B",1253),
    CRIMSON_STEM("minecraft:crimson_stem", "Crimson Stem", "B",1254),
    CRIMSON_TRAPDOOR("minecraft:crimson_trapdoor", "Crimson Trapdoor", "B",1255),
    CRIMSON_WALL_SIGN("minecraft:crimson_wall_sign", "Crimson Wall Sign", "B",1256),
    CROSSBOW("minecraft:crossbow", "Crossbow", "I",1257),
    CRYING_OBSIDIAN("minecraft:crying_obsidian", "Crying Obsidian", "B",1258),
    CUT_COPPER("minecraft:cut_copper", "Cut Copper", "B",1259),
    CUT_COPPER_SLAB("minecraft:cut_copper_slab", "Cut Copper Slab", "B",1260),
    CUT_COPPER_STAIRS("minecraft:cut_copper_stairs", "Cut Copper Stairs", "B",1261),
    CUT_RED_SANDSTONE("minecraft:cut_red_sandstone", "Cut Red Sandstone", "B",1262),
    CUT_RED_SANDSTONE_SLAB("minecraft:cut_red_sandstone_slab", "Cut Red Sandstone Slab", "B",1263),
    CUT_SANDSTONE("minecraft:cut_sandstone", "Cut Sandstone", "B",1264),
    CUT_SANDSTONE_SLAB("minecraft:cut_sandstone_slab", "Cut Sandstone Slab", "B",1265),
    CYAN_BANNER("minecraft:cyan_banner", "Cyan Banner", "B",1266),
    CYAN_BED("minecraft:cyan_bed", "Cyan Bed", "B",1267),
    CYAN_CANDLE("minecraft:cyan_candle", "Cyan Candle", "B",1268),
    CYAN_CANDLE_CAKE("minecraft:cyan_candle_cake", "Cyan Candle Cake", "B",1269),
    CYAN_CARPET("minecraft:cyan_carpet", "Cyan Crpet", "B",1270),
    CYAN_CONCRETE("minecraft:cyan_concrete", "Cyan Concrete", "B",1271),
    CYAN_CONCRETE_POWDER("minecraft:cyan_concrete_powder", "Cyan Concrete Powder", "B",1272),
    CYAN_DYE("minecraft:cyan_dye", "Cyan Dye", "I",1273),
    CYAN_GLAZED_TERRACOTTA("minecraft:cyan_glazed_terracotta", "Cyan Glazed Terracotta", "B",1274),
    CYAN_SHULKER_BOX("minecraft:cyan_shulker_box", "Cyan Shulker Box", "B",1275),
    CYAN_STAINED_GLASS("minecraft:cyan_stained_glass", "Cyan Stained Glass", "B",1276),
    CYAN_STAINED_GLASS_PANE("minecraft:cyan_stained_glass_pane", "Cyan Stained Glass Pane", "B",1277),
    CYAN_TERRACOTTA("minecraft:cyan_terracotta", "Cyan", "B",1278),
    CYAN_WALL_BANNER("minecraft:cyan_wall_banner", "Cyan Wall Banner", "B",1279),
    CYAN_WOOL("minecraft:cyan_wool", "Cyan Wool", "B",1280),
    DAMAGED_ANVIL("minecraft:damaged_anvil", "Damaged Anvil", "B",1281),
    DANDELION("minecraft:dandelion", "Löwenzahn", "B",1282),  //Ester Egg !
    DARK_OAK_BOAT("minecraft:dark_oak_boat", "Dark Oak Boat", "B",1283),
    DARK_OAK_BUTTON("minecraft:dark_oak_button", "Dark Oak Button", "B",1284),
    DARK_OAK_CHEST_BOAT("minecraft:dark_oak_chest_boat", "Dark Oak Chest Boat", "B",1285),
    DARK_OAK_DOOR("minecraft:dark_oak_door", "Dark Oak Door", "B",1286),
    DARK_OAK_FENCE("minecraft:dark_oak_fence", "Dark Oak Fence", "B",1287),
    DARK_OAK_FENCE_GATE("minecraft:dark_oak_fence_gate", "Dark Oak Fence Gate", "B",1288),
    DARK_OAK_LEAVES("minecraft:dark_oak_leaves", "Dark Oak Leaves", "B",1289),
    DARK_OAK_LOG("minecraft:dark_oak_log", "Dark Oak Log", "B",1290),
    DARK_OAK_PLANKS("minecraft:dark_oak_planks", "Dark Oak Planks", "B",1291),
    DARK_OAK_PRESSURE_PLATE("minecraft:dark_oak_pressure_plate", "Dark Oak Pressure Plate", "B",1292),
    DARK_OAK_SAPLING("minecraft:dark_oak_sapling", "Dark Oak Sapling", "I",1293),
    DARK_OAK_SIGN("minecraft:dark_oak_sign", "Dark Oak Sign", "B",1294),
    DARK_OAK_SLAB("minecraft:dark_oak_slab", "Dark Oak Slab", "B",1295),
    DARK_OAK_STAIRS("minecraft:dark_oak_stairs", "Dark Oak Stairs", "B",1296),
    DARK_OAK_TRAPDOOR("minecraft:dark_oak_trapdoor", "Dark Oak Trapdoor", "B",1297),
    DARK_OAK_WALL_SIGN("minecraft:dark_oak_wall_sign", "Dark Oak Wall Sign", "B",1298),
    DARK_OAK_WOOD("minecraft:dark_oak_wood", "Dark Oak Wood", "B",1299),
    DARK_PRISMARINE("minecraft:dark_prismarine", "Dark Prismarine", "B",1300),
    DARK_PRISMARINE_SLAB("minecraft:dark_prismarine_slab", "Dark Prismarine Slab", "B",1301),
    DARK_PRISMARINE_STAIRS("minecraft:dark_prismarine_stairs", "Dark Prismarine Stairs", "B",1302),
    DAYLIGHT_DETECTOR("minecraft:daylight_detector", "Daylight Detector", "B",1303),
    DEAD_BRAIN_CORAL("minecraft:dead_brain_coral", "Dead Brain Coral", "B",1304),
    DEAD_BRAIN_CORAL_BLOCK("minecraft:dead_brain_coral_block", "Dead Brain Coral Block", "B",1305),
    DEAD_BRAIN_CORAL_FAN("minecraft:dead_brain_coral_fan", "Dead Brain Coral Fan", "B",1306),
    DEAD_BRAIN_CORAL_WALL_FAN("minecraft:dead_brain_coral_wall_fan", "Dead Brain Coral Wall Fan", "B",1307),
    DEAD_BUBBLE_CORAL("minecraft:dead_bubble_coral", "Dead Bubble Coral", "B",1308),
    DEAD_BUBBLE_CORAL_BLOCK("minecraft:dead_bubble_coral_block", "Dead Bubble Coral Block", "B",1309),
    DEAD_BUBBLE_CORAL_FAN("minecraft:dead_bubble_coral_fan", "Dead Bubble Coral Fan", "B",1403),
    DEAD_BUBBLE_CORAL_WALL_FAN("minecraft:dead_bubble_coral_wall_fan", "Dead Bubble Coral Wall Fan", "B",1310),
    DEAD_BUSH("minecraft:dead_bush", "Dead Bush", "B",1311),
    DEAD_FIRE_CORAL("minecraft:dead_fire_coral", "Dead Fire Coral", "B",1312),
    DEAD_FIRE_CORAL_BLOCK("minecraft:dead_fire_coral_block", "Dead Fire Coral Block", "B",1313),
    DEAD_FIRE_CORAL_FAN("minecraft:dead_fire_coral_fan", "Dead Fire Coral Fan", "B",1314),
    DEAD_FIRE_CORAL_WALL_FAN("minecraft:dead_fire_coral_wall_fan", "Dead Fire Coral Wall Fan", "B",1315),
    DEAD_HORN_CORAL("minecraft:dead_horn_coral", "Dead Horn Coral", "B",1316),
    DEAD_HORN_CORAL_BLOCK("minecraft:dead_horn_coral_block", "Dead Horn Coral Block", "B",1317),
    DEAD_HORN_CORAL_FAN("minecraft:dead_horn_coral_fan", "Dead Horn Coral Fan", "B",1318),
    DEAD_HORN_CORAL_WALL_FAN("minecraft:dead_horn_coral_wall_fan", "Dead Horn Coral Wall Fan", "B",1319),
    DEAD_TUBE_CORAL("minecraft:dead_tube_coral", "Dead Tube Coral", "B",1320),
    DEAD_TUBE_CORAL_BLOCK("minecraft:dead_tube_coral_block", "Dead Tube Coral Block", "B",1321),
    DEAD_TUBE_CORAL_FAN("minecraft:dead_tube_coral_fan", "Dead Tube Coral Fan", "B",1322),
    DEAD_TUBE_CORAL_WALL_FAN("minecraft:dead_tube_coral_wall_fan", "Dead Tube Coral Wall Fan", "B",1323),
    DEBUG_STICK("minecraft:debug_stick", "Debug Stick", "B",1324);
//    DEEPSLATE(1325),
//    DEEPSLATE_BRICK_SLAB(1326),
//    DEEPSLATE_BRICK_STAIRS(1327),
//    DEEPSLATE_BRICK_WALL(1328),
//    DEEPSLATE_BRICKS(1329),
//    DEEPSLATE_COAL_ORE(1330),
//    DEEPSLATE_COPPER_ORE(1331),
//    DEEPSLATE_DIAMOND_ORE(1332),
//    DEEPSLATE_EMERALD_ORE(1333),
//    DEEPSLATE_GOLD_ORE(1334),
//    DEEPSLATE_IRON_ORE(1335),
//    DEEPSLATE_LAPIS_ORE(1336),
//    DEEPSLATE_REDSTONE_ORE(1337),
//    DEEPSLATE_TILE_SLAB(1338),
//    DEEPSLATE_TILE_STAIRS(1339),
//    DEEPSLATE_TILE_WALL(1340),
//    DEEPSLATE_TILES(1341),
//    DETECTOR_RAIL(1342),
//    DIAMOND(1343),
//    DIAMOND_AXE(1344),
//    DIAMOND_BLOCK(1345),
//    DIAMOND_BOOTS(1346),
//    DIAMOND_CHESTPLATE(1347),
//    DIAMOND_HOE(1348),
//    DIAMOND_HORSE_ARMOR(1349),
//    DIAMOND_LEGGINGS(1350),
//    DIAMOND_ORE(1351),
//    DIAMOND_PICKAXE(1352),
//    DIAMOND_SHOVEL(1353),
//    DIAMOND_SWORD(1354),
//    DIORITE(1355),
//    DIORITE_SLAB(1356),
//    DIORITE_STAIRS(1357),
//    DIORITE_WALL(1358),
//    DIRT(1359),
//    DIRT_PATH(1360),
//    DISC_FRAGMENT_5(1361),
//    DISPENSER(1362),
//    DOLPHIN_SPAWN_EGG(1363),
//    DONKEY_SPAWN_EGG(1364),
//    DRAGON_BREATH(1365),
//    DRAGON_EGG(1366),
//    DRAGON_HEAD(1367),
//    DRAGON_WALL_HEAD(1368),
//    DRIED_KELP(1369),
//    DRIED_KELP_BLOCK(1370),
//    DRIPSTONE_BLOCK(1371),
//    DROPPER(1372),
//    DROWNED_SPAWN_EGG(1373),
//    ECHO_SHARD(1374),
//    EGG(1375),
//    ELDER_GUARDIAN_SPAWN_EGG(1376),
//    ELYTRA(1377),
//    EMERALD(1378),
//    EMERALD_BLOCK(1379),
//    EMERALD_ORE(1380),
//    ENCHANTED_BOOK(1381),
//    ENCHANTED_GOLDEN_APPLE(1382),
//    ENCHANTING_TABLE(1383),
//    END_CRYSTAL(1384),
//    END_GATEWAY(1385),
//    END_PORTAL(1386),
//    END_PORTAL_FRAME(1387),
//    END_ROD(1388),
//    END_STONE(1389),
//    END_STONE_BRICK_SLAB(1390),
//    END_STONE_BRICK_STAIRS(1391),
//    END_STONE_BRICK_WALL(1392),
//    END_STONE_BRICKS(1393),
//    ENDER_CHEST(1394),
//    ENDER_EYE(1394),
//    ENDER_PEARL(1394),
//    ENDERMAN_SPAWN_EGG(1395),
//    ENDERMITE_SPAWN_EGG(1396),
//    EVOKER_SPAWN_EGG(1397),
//    EXPERIENCE_BOTTLE(1398),
//    EXPOSED_COPPER(1399),
//    EXPOSED_CUT_COPPER(1400),
//    EXPOSED_CUT_COPPER_SLAB(1401),
//    EXPOSED_CUT_COPPER_STAIRS(1402),
//    FARMLAND(1404),
//    FEATHER(),
//    FERMENTED_SPIDER_EYE(),
//    FERN(),
//    FILLED_MAP(),
//    FIRE(),
//    FIRE_CHARGE(),
//    FIRE_CORAL(),
//    FIRE_CORAL_BLOCK(),
//    FIRE_CORAL_FAN(),
//    FIRE_CORAL_WALL_FAN(),
//    FIREWORK_ROCKET(),
//    FIREWORK_STAR(),
//    FISHING_ROD(),
//    FLETCHING_TABLE(),
//    FLINT(),
//    FLINT_AND_STEEL(),
//    FLOWER_BANNER_PATTERN(),
//    FLOWER_POT(),
//    FLOWERING_AZALEA(),
//    FLOWERING_AZALEA_LEAVES(),
//    FOX_SPAWN_EGG(),
//    FROG_SPAWN_EGG(),
//    FROSTED_ICE(),
//    FURNACE(),
//    FURNACE_MINECART(),
//    GHAST_SPAWN_EGG(),
//    GHAST_TEAR(),
//    GILDED_BLACKSTONE(),
//    GLASS(),
//    GLASS_BOTTLE(),
//    GLASS_PANE(),
//    GLISTERING_MELON_SLICE(),
//    GLOBE_BANNER_PATTERN(),
//    GLOW_BERRIES(),
//    GLOW_INK_SAC(),
//    GLOW_ITEM_FRAME(),
//    GLOW_LICHEN(),
//    GLOW_SQUID_SPAWN_EGG(),
//    GLOWSTONE(),
//    GLOWSTONE_DUST(),
//    GOAT_HORN(),
//    GOAT_SPAWN_EGG(),
//    GOLD_BLOCK(),
//    GOLD_INGOT(),
//    GOLD_NUGGET(),
//    GOLD_ORE(),
//    GOLDEN_APPLE(),
//    GOLDEN_AXE(),
//    GOLDEN_BOOTS(),
//    GOLDEN_CARROT(),
//    GOLDEN_CHESTPLATE(),
//    GOLDEN_HELMET(),
//    GOLDEN_HOE(),
//    GOLDEN_HORSE_ARMOR(),
//    GOLDEN_LEGGINGS(),
//    GOLDEN_PICKAXE(),
//    GOLDEN_SHOVEL(),
//    GOLDEN_SWORD(),
//    GRANITE(),
//    GRANITE_SLAB(),
//    GRANITE_STAIRS(),
//    GRANITE_WALL(),
//    GRASS(),
//    GRASS_BLOCK(),
//    GRAVEL(),
//    GRAY_BANNER(),
//    GRAY_BED(),
//    GRAY_CANDLE(),
//    GRAY_CANDLE_CAKE(),
//    GRAY_CARPET(),
//    GRAY_CONCRETE(),
//    GRAY_CONCRETE_POWDER(),
//    GRAY_DYE(),
//    GRAY_GLAZED_TERRACOTTA(),
//    GRAY_SHULKER_BOX(),
//    GRAY_STAINED_GLASS(),
//    GRAY_STAINED_GLASS_PANE(),
//    GRAY_TERRACOTTA(),
//    GRAY_WALL_BANNER(),
//    GRAY_WOOL(),
//    GREEN_BANNER(),
//    GREEN_BED(),
//    GREEN_CANDLE(),
//    GREEN_CANDLE_CAKE(),
//    GREEN_CARPET(),
//    GREEN_CONCRETE(),
//    GREEN_CONCRETE_POWDER(),
//    GREEN_DYE(),
//    GREEN_GLAZED_TERRACOTTA(),
//    GREEN_SHULKER_BOX(),
//    GREEN_STAINED_GLASS(),
//    GREEN_STAINED_GLASS_PANE(),
//    GREEN_TERRACOTTA(),
//    GREEN_WALL_BANNER(),
//    GREEN_WOOL(),
//    GRINDSTONE(),
//    GUARDIAN_SPAWN_EGG(),
//    GUNPOWDER(),
//    HANGING_ROOTS(),
//    HAY_BLOCK(),
//    HEART_OF_THE_SEA(),
//    HEAVY_WEIGHTED_PRESSURE_PLATE(),
//    HOGLIN_SPAWN_EGG(),
//    HONEY_BLOCK(),
//    HONEY_BOTTLE(),
//    HONEYCOMB(),
//    HONEYCOMB_BLOCK(),
//    HOPPER(),
//    HOPPER_MINECART(),
//    HORN_CORAL(),
//    HORN_CORAL_BLOCK(),
//    HORN_CORAL_FAN(),
//    HORN_CORAL_WALL_FAN(),
//    HORSE_SPAWN_EGG(),
//    HUSK_SPAWN_EGG(),
//    ICE(),
//    INFESTED_CHISELED_STONE_BRICKS(),
//    INFESTED_COBBLESTONE(),
//    INFESTED_CRACKED_STONE_BRICKS(),
//    INFESTED_DEEPSLATE(),
//    INFESTED_MOSSY_STONE_BRICKS(),
//    INFESTED_STONE(),
//    INFESTED_STONE_BRICKS(),
//    INK_SAC(),
//    IRON_AXE(),
//    IRON_BARS(),
//    IRON_BLOCK(),
//    IRON_BOOTS(),
//    IRON_CHESTPLATE(),
//    IRON_DOOR(),
//    IRON_HELMET(),
//    IRON_HOE(),
//    IRON_HORSE_ARMOR(),
//    IRON_INGOT(),
//    IRON_LEGGINGS(),
//    IRON_NUGGET(),
//    IRON_ORE(),
//    IRON_PICKAXE(),
//    IRON_SHOVEL(),
//    IRON_SWORD(),
//    IRON_TRAPDOOR(),
//    ITEM_FRAME(),
//    JACK_O_LANTERN(),
//    JIGSAW(),
//    JUKEBOX(),
//    JUNGLE_BOAT(),
//    JUNGLE_BUTTON(),
//    JUNGLE_CHEST_BOAT(),
//    JUNGLE_DOOR(),
//    JUNGLE_FENCE(),
//    JUNGLE_FENCE_GATE(),
//    JUNGLE_LEAVES(),
//    JUNGLE_LOG(),
//    JUNGLE_PLANKS(),
//    JUNGLE_PRESSURE_PLATE(),
//    JUNGLE_SAPLING(),
//    JUNGLE_SIGN(),
//    JUNGLE_SLAB(),
//    JUNGLE_STAIRS(),
//    JUNGLE_TRAPDOOR(),
//    JUNGLE_WALL_SIGN(),
//    JUNGLE_WOOD(),
//    KELP(),
//    KELP_PLANT(),
//    KNOWLEDGE_BOOK(),
//    LADDER(),
//    LANTERN(),
//    LAPIS_BLOCK(),
//    LAPIS_LAZULI(),
//    LAPIS_ORE(),
//    LARGE_AMETHYST_BUD(),
//    LARGE_FERN(),
//    LAVA(),
//    LAVA_BUCKET(),
//    LAVA_CAULDRON(),
//    LEAD(),
//    LEATHER(),
//    LEATHER_BOOTS(),
//    LEATHER_CHESTPLATE(),
//    LEATHER_HELMET(),
//    LEATHER_HORSE_ARMOR(),
//    LEATHER_LEGGINGS(),
//    LECTERN();

    private String IdName;
    private String Name;
    private String type;
    private int Id;


    Material(String IdName, String Name, String type, int Id){
        this.Name = Name;
        this.IdName = IdName;
        this.type = type;
        this.Id = Id;
    }

     public String getIDName(){
        return IdName;
    }

    public String getName() {
        return Name;
    }
    public String getType(){
        return type;
    }

    public int getID(){
        return Id;
    }
}

